config/routes.rb
Rails.application.routes.draw do
  resources :owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/cars" => "cars#index"
  get "/cars/new" => "cars#new"
  get "/cars/:id" => "cars#show"
  post "/cars" => "cars#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/owner.rb
class Owner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
    render "cars/index"
  end
  
  def new
    render "cars/new"
  end

  def show
    @car = Car.find(params[:id])
    render "cars/show"
  end
  
  def create
    @car = Car.new(
      make: params[:make],
      model: params[:model],
      year: params[:year]
    )
    @car.save
    redirect_to "/cars/#{@car.id}"
  end
  
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: %i[ show edit update destroy ]

  # GET /owners or /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1 or /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners or /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to owner_url(@owner), notice: "Owner was successfully created." }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1 or /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to owner_url(@owner), notice: "Owner was successfully updated." }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1 or /owners/1.json
  def destroy
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to owners_url, notice: "Owner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def owner_params
      params.require(:owner).permit(:name, :years_owned)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/cars/index.html.erb
<p>This is the cars index page</p>


<% @cars.each do |car| %>
<p>Id: <%= car.id %></p>
<p>Make: <%= car.make %></p>
<a href="/cars/<%= car.id %>">More info</a>
<hr />
<% end %>

app/views/cars/new.html.erb
<p>Add a new car</p>

<form action="/cars" method="POST">
<p>Make: <input type = "text" name="make"></p>
<p>Model: <input type = "text" name="model"></p>
<p>Year: <input type = "text" name="year"></p>
<input type="submit" value="Add new car">
</form>

app/views/cars/show.html.erb
<p>This is the cars show page</p>

<p>Make: <%= @car.make %></p>
<p>Model: <%= @car.model %></p>
<p>Year: <%= @car.year %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <a href="/cars">Home</a>
      <a href="/cars/new">Add new car</a>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_with(model: owner) do |form| %>
  <% if owner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
        <% owner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :years_owned, style: "display: block" %>
    <%= form.number_field :years_owned %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/owners/_owner.html.erb
<div id="<%= dom_id owner %>">
  <p>
    <strong>Name:</strong>
    <%= owner.name %>
  </p>

  <p>
    <strong>Years owned:</strong>
    <%= owner.years_owned %>
  </p>

</div>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render "form", owner: @owner %>

<br>

<div>
  <%= link_to "Show this owner", @owner %> |
  <%= link_to "Back to owners", owners_path %>
</div>

app/views/owners/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Owners</h1>

<div id="owners">
  <% @owners.each do |owner| %>
    <%= render owner %>
    <p>
      <%= link_to "Show this owner", owner %>
    </p>
  <% end %>
</div>

<%= link_to "New owner", new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render "form", owner: @owner %>

<br>

<div>
  <%= link_to "Back to owners", owners_path %>
</div>

app/views/owners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @owner %>

<div>
  <%= link_to "Edit this owner", edit_owner_path(@owner) %> |
  <%= link_to "Back to owners", owners_path %>

  <%= button_to "Destroy this owner", @owner, method: :delete %>
</div>